/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Lista;

/**
 *
 * @author samantha
 */
public class AgregarLinea extends javax.swing.JFrame {

    private Lista linea = new Lista();
    
    /**
     * Creates new form AgregarLinea
     */
    public AgregarLinea() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inicioExit1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        inputEstacion = new javax.swing.JTextField();
        aggEstacion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        estacionesLinea = new javax.swing.JTextArea();
        volver = new javax.swing.JButton();
        cargarLinea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AGREGAR LÍNEA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        inicioExit1.setBackground(new java.awt.Color(204, 204, 255));
        inicioExit1.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        inicioExit1.setText("X");
        inicioExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioExit1ActionPerformed(evt);
            }
        });
        jPanel1.add(inicioExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 50, -1));

        jLabel2.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de la estación:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        inputEstacion.setBackground(new java.awt.Color(204, 204, 255));
        inputEstacion.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        inputEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEstacionActionPerformed(evt);
            }
        });
        jPanel1.add(inputEstacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 290, -1));

        aggEstacion.setBackground(new java.awt.Color(204, 204, 255));
        aggEstacion.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        aggEstacion.setText("Agregar estación");
        jPanel1.add(aggEstacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, -1));

        estacionesLinea.setBackground(new java.awt.Color(204, 204, 255));
        estacionesLinea.setColumns(20);
        estacionesLinea.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        estacionesLinea.setRows(5);
        jScrollPane1.setViewportView(estacionesLinea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 290, 200));

        volver.setBackground(new java.awt.Color(204, 204, 255));
        volver.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        volver.setText("<-- Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        cargarLinea.setBackground(new java.awt.Color(204, 204, 255));
        cargarLinea.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        cargarLinea.setText("Cargar línea");
        cargarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarLineaActionPerformed(evt);
            }
        });
        jPanel1.add(cargarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioExit1ActionPerformed
        dispose();
    }//GEN-LAST:event_inicioExit1ActionPerformed

    private void inputEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEstacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEstacionActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Menu menu = new Menu();
    }//GEN-LAST:event_volverActionPerformed

    private void cargarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarLineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargarLineaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarLinea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aggEstacion;
    private javax.swing.JButton cargarLinea;
    private javax.swing.JTextArea estacionesLinea;
    private javax.swing.JToggleButton inicioExit1;
    private javax.swing.JTextField inputEstacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
