/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Estacion;
import EDD.Lista;
import Funciones.Funcion;
import static Interfaces.Cargar.redApp;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author samantha
 */
public class AgregarLinea extends javax.swing.JFrame {

    private Lista linea = new Lista();
    private Lista conexion = new Lista();
    private Funcion func = new Funcion();
    
    DefaultComboBoxModel modeloLineaNueva = new DefaultComboBoxModel();
    DefaultComboBoxModel modeloRed = new DefaultComboBoxModel();
    
    /**
     * Creates new form AgregarLinea
     */
    public AgregarLinea() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        estacionesLinea.setText(func.mostrarEstaciones(linea));
        this.llenarComboRed();
    }
    
    private void llenarComboLinea(){
        modeloLineaNueva.removeAllElements();
        if(!linea.isEmpty()){
            for (int i = 0; i < linea.getSize(); i++) {
                Estacion estacion = (Estacion) linea.getValor(i);
                modeloLineaNueva.addElement(estacion.getNombre());
                
            }
        }
    }
    
    private void llenarComboRed(){
        modeloRed.removeAllElements();
        Lista estacionesRed = func.verEstaciones(redApp);
        if (estacionesRed != null) {
            for (int i = 0; i < estacionesRed.getSize(); i++) {
                String nombreEstacion = (String) estacionesRed.getValor(i);
                modeloRed.addElement(nombreEstacion);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inicioExit1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        inputEstacion = new javax.swing.JTextField();
        aggEstacion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        estacionesLinea = new javax.swing.JTextArea();
        volver = new javax.swing.JButton();
        cargarLinea = new javax.swing.JButton();
        estacionLinea = new javax.swing.JComboBox<>();
        estacionRed = new javax.swing.JComboBox<>();
        conexionConRed = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AGREGAR LÍNEA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        inicioExit1.setBackground(new java.awt.Color(204, 204, 255));
        inicioExit1.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        inicioExit1.setText("X");
        inicioExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioExit1ActionPerformed(evt);
            }
        });
        jPanel1.add(inicioExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 50, -1));

        jLabel2.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de la estación:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        inputEstacion.setBackground(new java.awt.Color(204, 204, 255));
        inputEstacion.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        inputEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEstacionActionPerformed(evt);
            }
        });
        jPanel1.add(inputEstacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 290, -1));

        aggEstacion.setBackground(new java.awt.Color(204, 204, 255));
        aggEstacion.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        aggEstacion.setText("Agregar estación");
        aggEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggEstacionActionPerformed(evt);
            }
        });
        jPanel1.add(aggEstacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 130, -1));

        estacionesLinea.setBackground(new java.awt.Color(204, 204, 255));
        estacionesLinea.setColumns(20);
        estacionesLinea.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        estacionesLinea.setRows(5);
        jScrollPane1.setViewportView(estacionesLinea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, 200));

        volver.setBackground(new java.awt.Color(204, 204, 255));
        volver.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        volver.setText("<-- Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        cargarLinea.setBackground(new java.awt.Color(204, 204, 255));
        cargarLinea.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        cargarLinea.setText("Cargar línea");
        cargarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarLineaActionPerformed(evt);
            }
        });
        jPanel1.add(cargarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        estacionLinea.setBackground(new java.awt.Color(204, 204, 255));
        estacionLinea.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        estacionLinea.setModel(modeloLineaNueva);
        jPanel1.add(estacionLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 180, -1));

        estacionRed.setBackground(new java.awt.Color(204, 204, 255));
        estacionRed.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        estacionRed.setModel(modeloRed);
        jPanel1.add(estacionRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 180, -1));

        conexionConRed.setBackground(new java.awt.Color(204, 204, 255));
        conexionConRed.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        conexionConRed.setText("Conexión con la red");
        conexionConRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conexionConRedActionPerformed(evt);
            }
        });
        jPanel1.add(conexionConRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 180, -1));

        jLabel3.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Estaciones de la red:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estaciones de la línea nueva:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Palatino", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Establcer la conexión entre la ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Palatino", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("nueva línea y la red existente.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Palatino", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PASO 1:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Palatino", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PASO 2:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioExit1ActionPerformed
        dispose();
    }//GEN-LAST:event_inicioExit1ActionPerformed

    private void inputEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEstacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEstacionActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Menu menu = new Menu();
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void cargarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarLineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargarLineaActionPerformed

    private void aggEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggEstacionActionPerformed
        //si el input donde va a escribir el usuario no está vacío
        if(!inputEstacion.getText().isEmpty()){
            //agarro el texto que escribió el usuario
            String nombre = inputEstacion.getText();
            //creo un objeto estacion
            Estacion estacion = new Estacion(nombre);
            //inserto el objeto a la lista linea
            linea.insertFinale(estacion);
            
            inputEstacion.setText("");//para que se vacie el input luego de que el usuario agregue la estacion
            
            this.llenarComboLinea();
            
            //mostrar en el text area
            estacionesLinea.setText(func.mostrarEstaciones(linea));
        }else{
            JOptionPane.showMessageDialog(null, "El componente está vacío");
        }
    }//GEN-LAST:event_aggEstacionActionPerformed

    private void conexionConRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conexionConRedActionPerformed
        String nombreEstacionLinea = (String)estacionLinea.getSelectedItem();
        String nombreEstacionRed = (String)estacionRed.getSelectedItem();
        
        func.agregarConexion(nombreEstacionLinea, nombreEstacionRed, conexion);
        
        //para probar si esta funcionando
        //si funcionaaaa :)
        //conexion.print();
    }//GEN-LAST:event_conexionConRedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarLinea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aggEstacion;
    private javax.swing.JButton cargarLinea;
    private javax.swing.JButton conexionConRed;
    private javax.swing.JComboBox<String> estacionLinea;
    private javax.swing.JComboBox<String> estacionRed;
    private javax.swing.JTextArea estacionesLinea;
    private javax.swing.JToggleButton inicioExit1;
    private javax.swing.JTextField inputEstacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
