/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;



import EDD.Grafo;
import Funciones.FuncionCargar;
import Interfaces.Menu;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author samantha
 */
public class Cargar extends javax.swing.JFrame {

    public static Grafo redApp = new Grafo();
    public static int valorT;
    /**
     * Creates new form Cargar
     */
    public Cargar() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cargarTitulo = new javax.swing.JLabel();
        cargarCargarRed = new javax.swing.JToggleButton();
        cargarBuscarArchivo = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        archivo = new javax.swing.JTextArea();
        ruta = new javax.swing.JTextField();
        inicioExit = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargarTitulo.setFont(new java.awt.Font("Palatino", 0, 36)); // NOI18N
        cargarTitulo.setForeground(new java.awt.Color(255, 255, 255));
        cargarTitulo.setText("Cargar red de transporte");
        jPanel3.add(cargarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        cargarCargarRed.setBackground(new java.awt.Color(204, 204, 255));
        cargarCargarRed.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        cargarCargarRed.setText("Cargar red");
        cargarCargarRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarCargarRedActionPerformed(evt);
            }
        });
        jPanel3.add(cargarCargarRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 300, -1));

        cargarBuscarArchivo.setBackground(new java.awt.Color(204, 204, 255));
        cargarBuscarArchivo.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        cargarBuscarArchivo.setText("Buscar archivo");
        cargarBuscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarBuscarArchivoActionPerformed(evt);
            }
        });
        jPanel3.add(cargarBuscarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        archivo.setBackground(new java.awt.Color(204, 204, 255));
        archivo.setColumns(20);
        archivo.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        archivo.setRows(5);
        jScrollPane1.setViewportView(archivo);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 300, 120));

        ruta.setBackground(new java.awt.Color(204, 204, 255));
        ruta.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutaActionPerformed(evt);
            }
        });
        jPanel3.add(ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 300, -1));

        inicioExit.setBackground(new java.awt.Color(204, 204, 255));
        inicioExit.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        inicioExit.setText("X");
        inicioExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioExitActionPerformed(evt);
            }
        });
        jPanel3.add(inicioExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 10, 50, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 360));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarCargarRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarCargarRedActionPerformed
        if (!archivo.getText().isEmpty()) {
            FuncionCargar func = new FuncionCargar();
            func.cargar(ruta.getText());
            
            redApp.setEstaciones(func.getEstaciones());
        
            System.out.println(redApp.toString());
        
            Menu menu = new Menu();
            
        }else{
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún archivo");  
        }
        
    }//GEN-LAST:event_cargarCargarRedActionPerformed

    private void rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutaActionPerformed

    private void cargarBuscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarBuscarArchivoActionPerformed
        JFileChooser fc = new JFileChooser();
        
        //para filtrar archivo json :)
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos JSON (*.json)","json");
        
        //asigno el filtro
        fc.setFileFilter(filtro);
        
        //se abre la ventana y guarda la opcion seleccionada
        int seleccion = fc.showOpenDialog(this);
        
        //si el usuario acepta
        if(seleccion == JFileChooser.APPROVE_OPTION){
            
            //para seleccionar el fichero
            File fichero = fc.getSelectedFile();
            
            //lo pasa a un JTextField
            ruta.setText(fichero.getAbsolutePath());
            try (FileReader fr = new FileReader(fichero)) {
                StringBuilder cadena = new StringBuilder();
                int valor = fr.read(); 
                
                //leer contenido del json
                while (valor!= -1){
                    cadena.append((char)valor);
                    valor = fr.read();
                }
                
                //Mostrar el archivo en el JTextArea
                archivo.setText(cadena.toString());
                
            } catch(IOException e1){
                   e1.printStackTrace();
            }
            
            }else {
                JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún archivo");
            }
        }

/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargar().setVisible(true);
            }
        });
    
    }//GEN-LAST:event_cargarBuscarArchivoActionPerformed

    private void inicioExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioExitActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea archivo;
    private javax.swing.JToggleButton cargarBuscarArchivo;
    private javax.swing.JToggleButton cargarCargarRed;
    private javax.swing.JLabel cargarTitulo;
    private javax.swing.JToggleButton inicioExit;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ruta;
    // End of variables declaration//GEN-END:variables
}
