/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Estacion;
import EDD.Lista;
import Funciones.Funcion;
import static Interfaces.Cargar.redApp;
import static Interfaces.Cargar.valorT;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author samantha
 */
public class Cobertura extends javax.swing.JFrame {

    /**
     * Creates new form Recorrido
     */
    private String nombreBusqueda = null;
    DefaultComboBoxModel modeloEstacionesBusq = new DefaultComboBoxModel();
    private Funcion func = new Funcion();
    
    public Cobertura() {
        initComponents();
        this.setVisible(true); //ventana visible para el usuario
        this.setResizable(false);//para que no se mueva su tamaño
        this.setLocationRelativeTo(null);//centra la ventana en la pantalla
        opcionesCobertura.add(opcionDFS);
        opcionesCobertura.add(opcionBFS);
        this.llenarComboBoxConSucursal();
        
    }

     private void llenarComboBoxConSucursal() {
        modeloEstacionesBusq.removeAllElements();
        //obtener lista de las estaciones sin sucursal
        Lista nombresConSucursal = func.estacionesConSucursal(redApp);
        
        
        //si la lista no esta vacia
        if (!nombresConSucursal.isEmpty()) {

            //llenamos el combo box 
            for (int i = 0; i < nombresConSucursal.getSize(); i++) {

                //casteo de lo que guarda cada uno de los nodos en esta lista en la posicion i
                String nombreActual = (String) nombresConSucursal.getValor(i);

                modeloEstacionesBusq.addElement(nombreActual);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volver = new javax.swing.JButton();
        opcionesCobertura = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inicioExit1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        estaciones = new javax.swing.JComboBox<>();
        opcionDFS = new javax.swing.JRadioButton();
        opcionBFS = new javax.swing.JRadioButton();
        revisarCobertura = new javax.swing.JButton();
        volver1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        volver.setBackground(new java.awt.Color(204, 204, 255));
        volver.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        volver.setText("<-- Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VER COBERTURA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        inicioExit1.setBackground(new java.awt.Color(204, 204, 255));
        inicioExit1.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        inicioExit1.setText("X");
        inicioExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioExit1ActionPerformed(evt);
            }
        });
        jPanel1.add(inicioExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 10, 50, -1));

        jLabel2.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccionar una estación:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        estaciones.setBackground(new java.awt.Color(204, 204, 255));
        estaciones.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        estaciones.setModel(modeloEstacionesBusq);
        jPanel1.add(estaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 210, -1));

        opcionDFS.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        opcionDFS.setForeground(new java.awt.Color(255, 255, 255));
        opcionDFS.setText("Cobertura DFS");
        opcionDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionDFSActionPerformed(evt);
            }
        });
        jPanel1.add(opcionDFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        opcionBFS.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        opcionBFS.setForeground(new java.awt.Color(255, 255, 255));
        opcionBFS.setText("Cobertura BFS");
        opcionBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionBFSActionPerformed(evt);
            }
        });
        jPanel1.add(opcionBFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        revisarCobertura.setBackground(new java.awt.Color(204, 204, 255));
        revisarCobertura.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        revisarCobertura.setText("Revisar cobertura");
        revisarCobertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revisarCoberturaActionPerformed(evt);
            }
        });
        jPanel1.add(revisarCobertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        volver1.setBackground(new java.awt.Color(204, 204, 255));
        volver1.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        volver1.setText("<-- Volver");
        volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver1ActionPerformed(evt);
            }
        });
        jPanel1.add(volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/cobertura6.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 360));
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioExit1ActionPerformed
        dispose();
    }//GEN-LAST:event_inicioExit1ActionPerformed

    private void opcionBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBFSActionPerformed
        nombreBusqueda = "BFS";
    }//GEN-LAST:event_opcionBFSActionPerformed

    private void opcionDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionDFSActionPerformed
        nombreBusqueda = "DFS";
    }//GEN-LAST:event_opcionDFSActionPerformed

    private void revisarCoberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revisarCoberturaActionPerformed
        if (nombreBusqueda!=null){
            String nombreEstacion = (String) estaciones.getSelectedItem();
            Estacion estacionInicial = redApp.search(nombreEstacion);
            if("BFS".equals(nombreBusqueda)){
                redApp.busquedaBFS(estacionInicial, valorT);
            }else{//nombreBusqueda == "DFS"
                redApp.busquedaDFS(estacionInicial, valorT);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Debes seleccionar un tipo de búsqueda");
        }
    }//GEN-LAST:event_revisarCoberturaActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Menu menu = new Menu();
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver1ActionPerformed
        Menu menu = new Menu();
        this.dispose();
    }//GEN-LAST:event_volver1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cobertura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> estaciones;
    private javax.swing.JToggleButton inicioExit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton opcionBFS;
    private javax.swing.JRadioButton opcionDFS;
    private javax.swing.ButtonGroup opcionesCobertura;
    private javax.swing.JButton revisarCobertura;
    private javax.swing.JButton volver;
    private javax.swing.JButton volver1;
    // End of variables declaration//GEN-END:variables
}
