/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author samantha
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inicioBienvenidos = new javax.swing.JLabel();
        inicioIniciarSistema = new javax.swing.JToggleButton();
        inicioIntegrantes = new javax.swing.JLabel();
        inicioExit = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicioBienvenidos.setFont(new java.awt.Font("Palatino", 1, 48)); // NOI18N
        inicioBienvenidos.setForeground(new java.awt.Color(255, 255, 255));
        inicioBienvenidos.setText("BIENVENIDOS");
        jPanel1.add(inicioBienvenidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        inicioIniciarSistema.setBackground(new java.awt.Color(204, 204, 255));
        inicioIniciarSistema.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        inicioIniciarSistema.setText("Iniciar sistema");
        inicioIniciarSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioIniciarSistemaActionPerformed(evt);
            }
        });
        jPanel1.add(inicioIniciarSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        inicioIntegrantes.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        inicioIntegrantes.setForeground(new java.awt.Color(255, 255, 255));
        inicioIntegrantes.setText("Integrantes: Samantha Castro, Fabiana Obelmejías, Gabriel Vizcarrondo");
        jPanel1.add(inicioIntegrantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        inicioExit.setBackground(new java.awt.Color(204, 204, 255));
        inicioExit.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        inicioExit.setText("X");
        inicioExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioExitActionPerformed(evt);
            }
        });
        jPanel1.add(inicioExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 10, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioIniciarSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioIniciarSistemaActionPerformed
        Cargar cargar = new Cargar();
        this.dispose();
    }//GEN-LAST:event_inicioIniciarSistemaActionPerformed

    private void inicioExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioExitActionPerformed
        dispose();
    }//GEN-LAST:event_inicioExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel inicioBienvenidos;
    private javax.swing.JToggleButton inicioExit;
    private javax.swing.JToggleButton inicioIniciarSistema;
    private javax.swing.JLabel inicioIntegrantes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
