/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import static Interfaces.Cargar.redApp;

/**
 *
 * @author samantha
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicioExit = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inicioExit1 = new javax.swing.JToggleButton();
        imagenSucursal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        imagenUpload = new javax.swing.JLabel();
        cargar = new javax.swing.JButton();
        establecerT = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        imagenT = new javax.swing.JLabel();
        imagenLinea = new javax.swing.JLabel();
        imagenGrafo = new javax.swing.JLabel();
        imagenRecorrido = new javax.swing.JLabel();

        inicioExit.setBackground(new java.awt.Color(204, 204, 255));
        inicioExit.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        inicioExit.setText("X");
        inicioExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioExitActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Palatino", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENÚ ◡̈");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        inicioExit1.setBackground(new java.awt.Color(204, 204, 255));
        inicioExit1.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        inicioExit1.setText("X");
        inicioExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioExit1ActionPerformed(evt);
            }
        });
        jPanel1.add(inicioExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 10, 50, -1));

        imagenSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/sucursal.png"))); // NOI18N
        jPanel1.add(imagenSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        jButton1.setText("Sucursal");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        imagenUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/cargar.png"))); // NOI18N
        jPanel1.add(imagenUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        cargar.setBackground(new java.awt.Color(204, 204, 255));
        cargar.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        cargar.setText("Cargar red");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });
        jPanel1.add(cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        establecerT.setBackground(new java.awt.Color(204, 204, 255));
        establecerT.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        establecerT.setText("Establecer T");
        establecerT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                establecerTActionPerformed(evt);
            }
        });
        jPanel1.add(establecerT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        jButton4.setText("Recorridos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        jButton5.setText("Agregar línea");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N
        jButton6.setText("Mostrar grafo");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        imagenT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/t2.png"))); // NOI18N
        jPanel1.add(imagenT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        imagenLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/linea (1).png"))); // NOI18N
        jPanel1.add(imagenLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        imagenGrafo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/grafooo.png"))); // NOI18N
        jPanel1.add(imagenGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        imagenRecorrido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/recorrido.png"))); // NOI18N
        jPanel1.add(imagenRecorrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioExitActionPerformed

    private void inicioExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioExit1ActionPerformed
        dispose();
    }//GEN-LAST:event_inicioExit1ActionPerformed

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        redApp.destruir();
        Cargar cargarRed = new Cargar();
        this.dispose();
    }//GEN-LAST:event_cargarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void establecerTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_establecerTActionPerformed
       EstablecerT establecerT = new EstablecerT ();
       this.dispose();
    }//GEN-LAST:event_establecerTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargar;
    private javax.swing.JButton establecerT;
    private javax.swing.JLabel imagenGrafo;
    private javax.swing.JLabel imagenLinea;
    private javax.swing.JLabel imagenRecorrido;
    private javax.swing.JLabel imagenSucursal;
    private javax.swing.JLabel imagenT;
    private javax.swing.JLabel imagenUpload;
    private javax.swing.JToggleButton inicioExit;
    private javax.swing.JToggleButton inicioExit1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
